// Code generated by hertz generator.

package main

import (
	"context"
	handler "gtools/biz/handler"
	"gtools/conf"
	"gtools/consts"
	"gtools/dal"
	"gtools/logger"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	conf.InitConfig()
	logger.Init(conf.GetLogger())
	dal.Init()

	h := server.Default(server.WithHostPorts(conf.GetConfig().Server.Port))
	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(RecoveryHandler)))
	register(h)
	h.Spin()
}

func RecoveryHandler(c context.Context, ctx *app.RequestContext, err interface{}, stack []byte) {
	defer func() {
		if r := recover(); r != nil {
			hlog.CtxErrorf(c, "[Recovery] panic recovered: %v", r)
		}
	}()
	hlog.CtxErrorf(c, "[Recovery] err=%v\nstack=%s", err, stack)
	hlog.CtxErrorf(c, "Client: %s", ctx.Request.Header.UserAgent())
	base := handler.BaseHandler{}
	base.ErrorResponse(c, ctx, &consts.SystemErr, nil)
	ctx.Abort()
}
